"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class Button(Widget):
    """
    Events:
        __on_press()
        __on_repeat()
        __on_release()
    """
    def __init__(self, parent, x, y, width, height, **kwargs) -> None:
        ...
    
    @property
    def is_pressed(self): # -> bool:
        ...
    
    def press(self): # -> None:
        ...
    


