"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class ColorPicker(Widget):
    """
    Events:
        __on_change(value)
    """
    def __init__(self, parent, x, y, value, *, with_shadow=..., **kwargs) -> None:
        ...
    
    @property
    def value(self): # -> None:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    def check_value(self, x, y): # -> int | None:
        ...
    


