"""
This type stub file was generated by pyright.
"""

from .toggle_button import ToggleButton

class ImageToggleButton(ToggleButton):
    """
    Events:
        __on_change()
    """
    def __init__(self, parent, x, y, img, sx, sy, **kwargs) -> None:
        ...
    


