"""
This type stub file was generated by pyright.
"""

from .button import Button

class ImageButton(Button):
    """
    Events:
        __on_press()
        __on_release()
    """
    def __init__(self, parent, x, y, img, sx, sy, **kwargs) -> None:
        ...
    


