"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class NumberPicker(Widget):
    """
    Events:
        __on_change(value)
    """
    def __init__(self, parent, x, y, min_value, max_value, value, **kwargs) -> None:
        ...
    
    @property
    def value(self): # -> None:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    


