"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class RadioButton(Widget):
    """
    Events:
        __on_change(value)
    """
    def __init__(self, parent, x, y, img, sx, sy, btn_count, value, **kwargs) -> None:
        ...
    
    @property
    def value(self): # -> None:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    def check_value(self, x, y): # -> int | None:
        ...
    


