"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class ScrollBar(Widget):
    """
    Events:
        __on_change(value)
    """
    HORIZONTAL = ...
    VERTICAL = ...
    def __init__(self, parent, x, y, size, direction, scroll_range, slider_range, value, *, with_shadow=..., **kwargs) -> None:
        ...
    
    @property
    def scroll_size(self):
        ...
    
    @property
    def slider_size(self): # -> int:
        ...
    
    @property
    def slider_pos(self): # -> int:
        ...
    
    @property
    def value(self): # -> None:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    


