"""
This type stub file was generated by pyright.
"""

from .button import Button

class TextButton(Button):
    """
    Events:
        __on_press()
        __on_release()
    """
    def __init__(self, parent, x, y, text, **kwargs) -> None:
        ...
    


