"""
This type stub file was generated by pyright.
"""

from .widget import Widget

class ToggleButton(Widget):
    """
    Events:
        __on_change(value)
    """
    def __init__(self, parent, x, y, width, height, **kwargs) -> None:
        ...
    
    @property
    def value(self): # -> bool:
        ...
    
    def press(self): # -> None:
        ...
    


