"""
This type stub file was generated by pyright.
"""

class Widget:
    """
    Events:
        __on_show()
        __on_hide()
        __on_enabled()
        __on_disabled()
        __on_move(x, y)
        __on_resize(width, height)
        __on_mouse_down(key, x, y)
        __on_mouse_up(key, x, y)
        __on_mouse_drag(key, x, y, dx, dy)
        __on_mouse_repeat(key, x, y)
        __on_mouse_click(key, x, y)
        __on_mouse_hover(x, y)
        __on_update()
        __on_draw()
    """
    class CaptureInfo:
        widget = ...
        key = ...
        time = ...
        press_pos = ...
        last_pos = ...
    
    
    _capture_info = ...
    def __init__(self, parent, x, y, width, height, *, is_visible=..., is_enabled=...) -> None:
        ...
    
    @property
    def parent(self): # -> None:
        ...
    
    @parent.setter
    def parent(self, value): # -> None:
        ...
    
    @property
    def x(self): # -> None:
        ...
    
    @property
    def y(self): # -> None:
        ...
    
    @property
    def width(self): # -> None:
        ...
    
    @property
    def height(self): # -> None:
        ...
    
    @property
    def is_visible(self): # -> None:
        ...
    
    @is_visible.setter
    def is_visible(self, value): # -> None:
        ...
    
    @property
    def is_enabled(self): # -> None:
        ...
    
    @is_enabled.setter
    def is_enabled(self, value): # -> None:
        ...
    
    def add_event_handler(self, event, handler): # -> None:
        ...
    
    def remove_event_handler(self, event, handler): # -> None:
        ...
    
    def call_event_handler(self, event, *args): # -> None:
        ...
    
    def is_hit(self, x, y):
        ...
    
    def move(self, x, y): # -> None:
        ...
    
    def resize(self, width, height): # -> None:
        ...
    
    @staticmethod
    def draw_panel(x, y, width, height, *, with_shadow=...): # -> None:
        ...
    
    def update_widgets(self): # -> None:
        ...
    
    def draw_widgets(self): # -> None:
        ...
    


