"""
This type stub file was generated by pyright.
"""

from pyxel.ui import Widget

class Editor(Widget):
    """
    Events:
        __on_undo(data)
        __on_redo(data)
        __on_drop(filenames)
    """
    def __init__(self, parent) -> None:
        ...
    
    @property
    def help_message(self):
        ...
    
    @help_message.setter
    def help_message(self, value): # -> None:
        ...
    
    @property
    def can_undo(self): # -> bool:
        ...
    
    @property
    def can_redo(self): # -> bool:
        ...
    
    def undo(self): # -> None:
        ...
    
    def redo(self): # -> None:
        ...
    
    def add_history(self, data): # -> None:
        ...
    
    def reset_history(self): # -> None:
        ...
    
    def add_number_picker_help(self, number_picker): # -> None:
        ...
    
    def check_tool_button_shortcuts(self): # -> None:
        ...
    
    def add_tool_button_help(self, tool_button): # -> None:
        ...
    


