"""
This type stub file was generated by pyright.
"""

from pyxel.ui import Widget

class ImagePanel(Widget):
    def __init__(self, parent, *, is_tilemap_mode) -> None:
        ...
    
    @property
    def focused_tiles(self): # -> list[Unknown]:
        ...
    
    def set_focus(self, x, y): # -> None:
        ...
    


