"""
This type stub file was generated by pyright.
"""

from .editor import Editor

class MusicEditor(Editor):
    def __init__(self, parent) -> None:
        ...
    
    @property
    def music(self): # -> None:
        ...
    
    @property
    def is_playing(self): # -> bool:
        ...
    
    def play_pos(self, ch): # -> int:
        ...
    
    def get_data(self, value): # -> List[int]:
        ...
    
    def add_pre_history(self, x, y): # -> None:
        ...
    
    def add_post_history(self, x, y): # -> None:
        ...
    


