"""
This type stub file was generated by pyright.
"""

from pyxel.ui import Widget

class MusicField(Widget):
    def __init__(self, parent, x, y, ch) -> None:
        ...
    
    @property
    def data(self):
        ...
    


