"""
This type stub file was generated by pyright.
"""

from .editor import Editor

class SoundEditor(Editor):
    def __init__(self, parent) -> None:
        ...
    
    @property
    def keyboard_note(self): # -> int | None:
        ...
    
    @property
    def is_playing(self): # -> bool | None:
        ...
    
    @property
    def play_pos(self): # -> int:
        ...
    
    def get_data(self, index): # -> List[int]:
        ...
    
    def add_pre_history(self, x, y): # -> None:
        ...
    
    def add_post_history(self, x, y): # -> None:
        ...
    


