"""
This type stub file was generated by pyright.
"""

from pyxel.ui import Widget

tone_key_table = ...
effect_key_table = ...
class SoundField(Widget):
    def __init__(self, parent) -> None:
        ...
    


