"""
This type stub file was generated by pyright.
"""

from .editor import Editor

class TileMapEditor(Editor):
    def __init__(self, parent) -> None:
        ...
    
    @property
    def tilemap(self): # -> None:
        ...
    
    @tilemap.setter
    def tilemap(self, value): # -> None:
        ...
    
    @property
    def color(self): # -> list[Unknown]:
        ...
    
    @color.setter
    def color(self, value): # -> None:
        ...
    
    @property
    def tool(self): # -> None:
        ...
    
    @tool.setter
    def tool(self, value): # -> None:
        ...
    
    @property
    def image(self): # -> None:
        ...
    
    @image.setter
    def image(self, value): # -> None:
        ...
    
    @property
    def drawing_x(self): # -> int:
        ...
    
    @drawing_x.setter
    def drawing_x(self, value): # -> None:
        ...
    
    @property
    def drawing_y(self): # -> int:
        ...
    
    @drawing_y.setter
    def drawing_y(self, value): # -> None:
        ...
    


