"""
This type stub file was generated by pyright.
"""

def get_array2d_size(arr): # -> tuple[int, int] | tuple[Literal[256], Literal[256]]:
    ...

def new_array2d(width, height): # -> list[Unknown]:
    ...

def fill_array2d(arr, val): # -> None:
    ...

def slice_array2d(arr, x, y, width, height): # -> list[Unknown]:
    ...

def copy_array2d(dst, dx, dy, src, sx=..., sy=..., cw=..., ch=...): # -> None:
    ...

